"""add year

Revision ID: 97f947ea0bfd
Revises: 32e135bdf26a
Create Date: 2023-02-15 11:27:24.686698

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '97f947ea0bfd'
down_revision = '32e135bdf26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    #op.alter_column('song', 'id',
    #           existing_type=sa.INTEGER(),
    #           nullable=True,
    #           autoincrement=True)
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_year'), table_name='song')
    #op.alter_column('song', 'id',
    #           existing_type=sa.INTEGER(),
    #           nullable=False,
    #           autoincrement=True)
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
